### ISSUE TITLE
Improvements to the Download page

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-website#31]
Now that the About page is deployed, I think we should standardize the look and feel of additional pages in our website.

So, these are my suggestions to do that for the Download page:

* Title: Download Spyder
* Text: Select the package you want to download from the links below. Or visit our [releases page](https://github.com/spyder-ide/spyder/releases) on GitHub.
* Remove the horizontal line and `Available for`.

**Comment by conradolandia** [comment]
PR #32 tries to solve this issue.
