### ISSUE TITLE
Backticks added in CSS around monospace text in Markdown blogs

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder-website#36]
@ccordoba12 and I noticed that backticks are mistakenly displayed around monospace text, at least in the blog where we were able to check for it, when that shouldn't be the case. For example, on the [Conda-based installers installers[sic] post](https://www.spyder-ide.org/blog/cbi-installers/):

![image](https://github.com/user-attachments/assets/6cb6a39b-9ae6-4273-80b1-0ea4cceb7989)

For the corresponding [source code](https://github.com/spyder-ide/spyder-website/blob/c66130173d607c2e5754d9eb0c0483df62cf8c87/src/routes/blog/cbi-installers/%2Bpage.md?plain=1#L24):

```markdown
If you are a macOS user, you will now have a `.pkg` package installer instead of a `.dmg` disk image.
Rather than drag-and-drop the application to the `Applications` folder, the `.pkg` installer provides a graphical interface that will guide you through the installation process with more flexibility.
```

The backticks are not in the actual content, but are instead added the `::before` and `::after` pseudo-elements of the `<code>` node via CSS `content`:

![image](https://github.com/user-attachments/assets/ab175178-8815-46fe-b4af-077af46c0862)

Could this be fixed? Thanks!

**Comment by conradolandia** [comment]
Solved by #37
